# -*- coding: utf-8 -*-
"""halo_dunia.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/18erUSr1lWq3MHvvOp-PEcX1qVF1aw8GU
"""

print('Halo Dunia!')